export const RECEIVE_FRIENDS = 'RECEIVE_FRIENDS';
export const RECEIVE_EXPENSES = 'RECEIVE_EXPENSES';
export const RECEIVE_DEBTS = 'RECEIVE_DEBTS';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const ERROR_ADD_EXPENSE = 'ERROR_ADD_EXPENSE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const ERROR_LOGIN = 'ERROR_LOGIN';
