export const INVITE_FRIEND = 'INVITE_FRIEND';
export const ACCEPT_FRIEND = 'ACCEPT_FRIEND';
export const DECLINE_FRIEND = 'DECLINE_FRIEND';
export const RECEIVE_FRIENDS = 'RECEIVE_FRIENDS';

export const ADD_EXPENSE = 'ADD_EXPENSE';
export const RECEIVE_EXPENSES = 'RECEIVE_EXPENSES';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const ERROR_LOGIN = 'ERROR_LOGIN';
