export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const ERROR_SIGNUP = 'ERROR_SIGNUP';
export const ERROR_LOGIN = 'ERROR_LOGIN';
