# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5ed2162751c544b947dad3b1163cff5e3d25b641382944c08451c1d9e6e0fe1186446467ea1b3b2798dbce16604c8e4a3c906f26622607646761d6f2c7d5719

test:
  secret_key_base: 150dd1269fe3be0024ec8271aec90a41e30b13787c4b09d26daeb8e475f48f48d5f5375bb3223d81756e37bb725d31cd099d37ab7fc88e5630828fa06e6d8de6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
